"""
Seeds the quotes table with curated motivational quotes.
Run this once: python seed_quotes.py
"""
from app.database import SessionLocal, engine, Base
from app.models.quote import Quote

# Make sure the table exists before inserting
Base.metadata.create_all(bind=engine, tables=[Quote.__table__])

quotes_data = [
    {"text": "The willingness to show up changes us. It makes us a little braver each time.", "author": None},
    {"text": "The formula for success is 2% talent, 8% luck, and 90% of showing up every day.", "author": None},
    {"text": "What we regret most are our failures of courage, whether it's the courage to be kinder, to show up, to say how we feel, to set boundaries, to be good to ourselves, to say yes to something scary.", "author": None},
    {"text": "Persistence is showing up even when you don't feel like it, failing and rising again, learning, adjusting, and pushing forward.", "author": None},
    {"text": "Persistence compounds. One more try, one more day, one more effort—that could be your breakthrough.", "author": None},
    {"text": "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us.", "author": None},
    {"text": "One day, in retrospect, the years of struggle will strike you as the most beautiful.", "author": None},
    {"text": "It's only after you've stepped outside your comfort zone that you begin to change, grow, and transform.", "author": "Roy T. Bennett"},
    {"text": "Your hardest times often lead to the greatest moments of your life. Keep going. Tough situations build strong people in the end.", "author": "Roy T. Bennett"},
    {"text": "Don't be afraid of your fears. They're not there to scare you. They're there to let you know that something is worth it.", "author": None},
    {"text": "Self-care is never a selfish act — it is simply stewardship of the only gift I have, the gift I was put on earth to offer to others.", "author": "Parker Palmer"},
    {"text": "Pain is temporary. It may last a minute, or an hour, or a day, or a year, but eventually it will subside and something else will take its place. If I quit, however, it lasts forever.", "author": None},
    {"text": "If you quit on the process, you are quitting on the result.", "author": None},
    {"text": "If you quit ONCE it becomes a habit. Never quit!", "author": "Michael Jordan"},
    {"text": "Consistency is the only path to success; quitting prematurely only ensures failure.", "author": None},
    {"text": "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", "author": "Muhammad Ali"},
    {"text": "We are what we repeatedly do. Excellence then is not an act but a habit.", "author": "Aristotle"},
    {"text": "The body achieves what the mind believes.", "author": "Napoleon Hill"},
    {"text": "The hard days are the best because that's when champions are made, so if you push through, you can push through anything.", "author": "Dana Vollmer"},
    {"text": "If you don't find the time, if you don't do the work, you don't get the results.", "author": "Arnold Schwarzenegger"},
    {"text": "Dead last finish is greater than did not finish, which trumps did not start.", "author": None},
    {"text": "Push harder than yesterday if you want a different tomorrow.", "author": "Vincent Williams Sr."},
    {"text": "The real workout starts when you want to stop.", "author": "Ronnie Coleman"},
    {"text": "Take care of your body. It's the only place you have to live.", "author": "Jim Rohn"},
    {"text": "I've failed over and over again in my life and that is why I succeed.", "author": "Michael Jordan"},
    {"text": "Once you are exercising regularly, the hardest thing is to stop it.", "author": "Erin Gray"},
    {"text": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"text": "Exercise should be regarded as tribute to the heart.", "author": "Gene Tunney"},
    {"text": "You're going to have to let it hurt. Let it suck. The harder you work, the better you will look. Your appearance isn't parallel to how heavy you lift, it's parallel to how hard you work.", "author": "Joe Manganiello"},
    {"text": "Most people fail, not because of lack of desire, but because of lack of commitment.", "author": "Vince Lombardi"},
    {"text": "You miss one hundred percent of the shots you don't take.", "author": "Wayne Gretzky"},
    {"text": "If something stands between you and your success, move it. Never be denied.", "author": "Dwayne 'The Rock' Johnson"},
    {"text": "All progress takes place outside the comfort zone.", "author": "Michael John Bobak"},
    {"text": "Just believe in yourself. Even if you don't, just pretend that you do and at some point, you will.", "author": "Venus Williams"},
    {"text": "The harder you work and the more prepared you are for something, you're going to be able to persevere through anything.", "author": "Carli Lloyd"},
    {"text": "Enduring means accepting. Accepting things as they are and not as you would wish them to be, and then looking ahead, not behind.", "author": "Rafael Nadal"},
    {"text": "If you want something you've never had, you must be willing to do something you've never done.", "author": "Thomas Jefferson"},
    {"text": "The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character.", "author": "Arnold Schwarzenegger"},
    {"text": "Continuous improvement is better than delayed perfection.", "author": "Mark Twain"},
    {"text": "Once you learn to quit, it becomes a habit.", "author": "Vince Lombardi"},
    {"text": "It's hard to beat a person who never gives up.", "author": "Babe Ruth"},
    {"text": "Do something today that your future self will thank you for.", "author": "Sean Patrick Flanery"},
    {"text": "Success is usually the culmination of controlling failure.", "author": "Sylvester Stallone"},
    {"text": "Think of your workouts as important meetings you schedule with yourself. Bosses don't cancel.", "author": None},
    {"text": "Workout till you feel that pain and soreness in muscles. This one is good pain. No pain, no gain.", "author": None},
    {"text": "Confidence comes from discipline and training.", "author": "Robert Kiyosaki"},
    {"text": "I don't count my sit-ups. I only start counting when it starts hurting because they're the only ones that count.", "author": "Muhammad Ali"},
    {"text": "What hurts today makes you stronger tomorrow.", "author": "Jay Cutler"},
    {"text": "Strength does not come from physical capacity. It comes from an indomitable will.", "author": "Mahatma Gandhi"},
    {"text": "You must expect things of yourself before you can do them.", "author": "Michael Jordan"},
    {"text": "The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.", "author": "Arnold Schwarzenegger"},
    {"text": "If you fail to prepare, you're prepared to fail.", "author": "Mark Spitz"},
    {"text": "Motivation is what gets you started. Habit is what keeps you going.", "author": "Jim Ryun"},
    {"text": "A champion is someone who gets up when they can't.", "author": "Jack Dempsey"},
    {"text": "The difference between the impossible and the possible lies in a person's determination.", "author": "Tommy Lasorda"},
    {"text": "When you have a clear vision of your goal, it's easier to take the first step toward it.", "author": "LL Cool J"},
    {"text": "When I feel tired, I just think about how great I will feel once I finally reach my goal.", "author": "Michael Phelps"},
    {"text": "You have to think about it before you can do it. The mind is what makes it all possible.", "author": "Kai Greene"},
    {"text": "The only bad workout is the one that didn't happen.", "author": None},
    {"text": "Don't be afraid of failure. This is the way to succeed.", "author": "LeBron James"},
    {"text": "You should never stay at the same level. Always push yourself to the next.", "author": "Marnelli Dimzon"},
    {"text": "You did not wake up today to be mediocre.", "author": "Robin Arzon"},
    {"text": "Action is the foundational key to all success.", "author": "Pablo Picasso"},
    {"text": "If it doesn't challenge you, it doesn't change you.", "author": "Fred DeVito"},
    {"text": "You can either suffer the pain of discipline or the pain of regret.", "author": "Jim Rohn"},
    {"text": "We can push ourselves further. We always have more to give.", "author": "Simone Biles"},
    {"text": "If you want to be the best, you have to do things other people aren't willing to do.", "author": "Michael Phelps"},
    {"text": "Every champion was once a contender who refused to give up.", "author": "Rocky Balboa"},
    {"text": "The difference between try and triumph is a little 'umph'.", "author": "Marvin Phillips"},
    {"text": "If you are not pissed off for greatness, that just means you're okay with being mediocre.", "author": "Ray Lewis"},
    {"text": "Keep working even when no one is watching.", "author": "Alex Morgan"},
    {"text": "Your health account, your bank account, they're the same thing. The more you put in, the more you can take out. Exercise is king and nutrition is queen. Together you have a kingdom.", "author": "Jack LaLanne"},
    {"text": "Don't dream of winning. Train for it!", "author": "Mo Farah"},
    {"text": "Most people give up right before the big break comes. Don't let that person be you.", "author": "Michael Boyle"},
    {"text": "Discipline is the bridge between goals and accomplishment.", "author": "Jim Rohn"},
    {"text": "Fitness is not about being better than someone else. It's about being better than you used to be.", "author": "Khloe Kardashian"},
    {"text": "Keep listening to your body. It will tell you when something is not okay.", "author": "Emily Infeld"},
    {"text": "Whether you think you can, or you think you can't, you are right.", "author": "Henry Ford"},
    {"text": "All our dreams can come true if we have the courage to pursue them.", "author": "Walt Disney"},
    {"text": "Great things come from hard work and perseverance. No excuses.", "author": "Kobe Bryant"},
    {"text": "Always make a total effort, even when the odds are against you.", "author": "Arnold Palmer"},
    {"text": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill"},
    {"text": "Your mind will quit a thousand times before your body will.", "author": "Reginald Red"},
    {"text": "I've grown most not from victories, but setbacks. If winning is God's reward, then losing is how he teaches us.", "author": "Serena Williams"},
    {"text": "Set your goals high, and don't stop until you get there.", "author": "Bo Jackson"},
    {"text": "Physical fitness can neither be achieved by wishful thinking nor outright purchase.", "author": "Joseph Pilates"},
    {"text": "You shall gain, but you shall pay with sweat, blood, and vomit.", "author": "Pavel Tsatsouline"},
    {"text": "You have to push past your perceived limits, push past that point you thought was as far as you can go.", "author": "Drew Brees"},
    {"text": "Get ready, be prepared. So when opportunities finally show themselves, you'll be able to own them.", "author": "Hannah Gabriels"},
    {"text": "Be humble. Be hungry. And always be the hardest worker in the room.", "author": "Dwayne 'The Rock' Johnson"},
    {"text": "Some people want it to happen, some wish it would happen, others make it happen.", "author": "Michael Jordan"},
    {"text": "A year from now you may wish you had started today.", "author": "Karen Lamb"},
    {"text": "A goal is just an awesome way to force growth on yourself.", "author": "Deena Kastor"},
    {"text": "If you do not believe in yourself, no one will do it for you.", "author": "Kobe Bryant"},
    {"text": "Our bodies are gardens, our wills are our gardeners.", "author": "William Shakespeare"},
    {"text": "Get comfortable with being uncomfortable!", "author": "Jillian Michaels"},
    {"text": "Time, effort, sacrifice, and sweat. How will you pay for your goals?", "author": "Usain Bolt"},
    {"text": "He who is not courageous enough to take risks will accomplish nothing in life.", "author": "Muhammad Ali"},
    {"text": "It's supposed to be hard. If it wasn't hard, everyone would do it. The hard is what makes it great.", "author": "Tom Hanks"},
    {"text": "The purpose of training is to tighten up the slack, toughen the body, and polish the spirit.", "author": "Morihei Ueshiba"},
    {"text": "Put all excuses aside and remember this: you are capable.", "author": "Zig Ziglar"},
    {"text": "The groundwork for all happiness is good health.", "author": "Leigh Hunt"},
    {"text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
    {"text": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon"},
    {"text": "The clock is ticking. Are you becoming the person you want to be?", "author": "Greg Plitt"},
    {"text": "The successful warrior is the average man, with laser-like focus.", "author": "Bruce Lee"},
    {"text": "Pain is temporary. Quitting lasts forever.", "author": "Lance Armstrong"},
    {"text": "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", "author": "John F. Kennedy"},
    {"text": "No matter how many mistakes you make or how slow you progress, you are still way ahead of everyone who isn't trying.", "author": "Tony Robbins"},
    {"text": "Making excuses burns zero calories per hour.", "author": None},
    {"text": "The only person you are destined to become is the person you decide to be.", "author": "Ralph Waldo Emerson"},
    {"text": "Great works are performed, not by strength, but by perseverance.", "author": "Samuel Johnson"},
    {"text": "All you need in this life is ignorance and confidence, and then success is sure.", "author": "Mark Twain"},
    {"text": "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", "author": "Leonardo da Vinci"},
    {"text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier"},
    {"text": "Challenges are what make life interesting and overcoming them is what makes life meaningful.", "author": None},
    {"text": "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author": "Aristotle"},
    {"text": "I am not a product of my circumstances, I am a product of my decisions.", "author": None},
    {"text": "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, dream, discover.", "author": "Mark Twain"},
    {"text": "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "author": "Michael Jordan"},
    {"text": "Don't be afraid of being different. Be afraid of being the same as everyone else.", "author": None},
    {"text": "I will succeed, because I am willing to fail more times than you are willing to try.", "author": None},
    {"text": "Don't get discouraged, it is often the last key that opens the lock.", "author": None},
    {"text": "It's always too soon to quit!", "author": "Norman Vincent Peale"},
    {"text": "Life begins at the end of your comfort zone.", "author": None},
    {"text": "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", "author": "Helen Keller"},
    {"text": "Achievement is usually born of great sacrifice, and is never the result of selfishness.", "author": "Napoleon Hill"},
    {"text": "Keep your face always toward the sunshine, and shadows will fall behind you.", "author": "Walt Whitman"},
    {"text": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson"},
    {"text": "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.", "author": "Dale Carnegie"},
    {"text": "The only time you fail is when you fall down and stay down.", "author": "Stephen Richards"},
    {"text": "It always seems impossible until it's done.", "author": "Nelson Mandela"},
    {"text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu"},
    {"text": "How long should you try? Until.", "author": "Jim Rohn"},
    {"text": "Winners never quit, and quitters never win.", "author": "Vince Lombardi"},
    {"text": "Believe you can, and you're halfway there.", "author": "Theodore Roosevelt"},
    {"text": "The greater the obstacle, the more glory in overcoming it.", "author": "Molière"},
    {"text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"},
    {"text": "Successful men and women keep moving. They make mistakes, but they don't quit.", "author": "Conrad Hilton"},
    {"text": "Fall seven times; stand up eight.", "author": "Japanese Proverb"},
    {"text": "Quitting is the only failure.", "author": None},
    {"text": "The air is thinner as we get closer to the top of the mountain.", "author": None},
    {"text": "Many of life's failures are people who did not realize how close they were to success when they gave up.", "author": "Thomas A. Edison"},
    {"text": "The opposite of quitting is to persevere, just wait a little longer, things will turn around soon.", "author": "Dr. Lucas D. Shallua"},
    {"text": "When quitting becomes routine, you won't think twice about giving up the next time.", "author": "Frank Sonnenberg"},
    {"text": "You are about to succeed when the urge to quit is the greatest.", "author": None},
    {"text": "The only way to define your limits is by going beyond them.", "author": "Arthur C. Clarke"},
    {"text": "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.", "author": "Jack LaLanne"},
    {"text": "No pain, no gain. Shut up and train.", "author": None},
    {"text": "Sweat is fat crying.", "author": None},
    {"text": "Your body can stand almost anything. It's your mind that you have to convince.", "author": "Andrew Murphy"},
    {"text": "Don't limit your challenges, challenge your limits.", "author": "Jerry Dunn"},
    {"text": "You're only one workout away from a good mood.", "author": None},
    {"text": "To give anything less than your best is to sacrifice the gift.", "author": "Steve Prefontaine"},
    {"text": "It's not about having time. It's about making time.", "author": None},
    {"text": "Don't count the days, make the days count.", "author": "Muhammad Ali"},
    {"text": "If it doesn't challenge you, it won't change you.", "author": "Fred DeVito"},
    {"text": "The pain you feel today will be the strength you feel tomorrow.", "author": None},
    {"text": "The only place success comes before work is in the dictionary.", "author": "Vidal Sassoon"},
    {"text": "When you feel like quitting, think about why you started.", "author": None},
    {"text": "It's supposed to be hard. If it were easy, everyone would do it.", "author": "Tom Hanks"},
    {"text": "You can have results or excuses, but not both.", "author": "Arnold Schwarzenegger"},
    {"text": "Fitness is like a relationship. You can't cheat and expect it to work.", "author": None},
    {"text": "Training gives us an outlet for suppressed energies created by stress and thus tones the spirit just as exercise conditions the body.", "author": "Arnold Schwarzenegger"},
    {"text": "Hard work beats talent when talent doesn't work hard.", "author": "Tim Notke"},
    {"text": "A one hour workout is 4% of your day. No excuses.", "author": None},
    {"text": "Respect your body. It's the only one you get.", "author": None},
    {"text": "You don't have to be extreme, just consistent.", "author": None},
    {"text": "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.", "author": "Arnold Schwarzenegger"},
    {"text": "If you think lifting is dangerous, try being weak. Being weak is dangerous.", "author": "Bret Contreras"},
    {"text": "If you work really hard, and you're kind, amazing things will happen.", "author": "Conan O'Brien"},
    {"text": "Opportunities are usually disguised as hard work, so most people don't recognize them.", "author": "Ann Landers"},
    {"text": "There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.", "author": "Michael Phelps"},
    {"text": "You're not obligated to win. You're obligated to keep trying to do the best you can every day.", "author": "Marian Wright Edelman"},
    {"text": "I'm a great believer in luck, and I find the harder I work the more I have of it.", "author": "Thomas Jefferson"},
    {"text": "I do not know anyone who has got to the top without hard work. That is the recipe. It will not always get you to the top, but should get you pretty near.", "author": "Margaret Thatcher"},
    {"text": "When you live for a strong purpose, then hard work isn't an option. It's a necessity.", "author": "Steve Pavlina"},
    {"text": "It's not about money or connections. It's the willingness to outwork and outlearn everyone.", "author": "Mark Cuban"},
    {"text": "Always go with the choice that scares you the most, because that's the one that is going to require the most from you.", "author": "Caroline Myss"},
    {"text": "Happiness is the real sense of fulfillment that comes from hard work.", "author": "Joseph Roland Barbera"},
    {"text": "This is the real secret of life — to be completely engaged with what you are doing in the here and now. Instead of calling it work, realize it is play.", "author": "Alan Watts"},
    {"text": "Don't settle for average. Bring your best to the moment. Then, whether it fails or succeeds, at least you know you gave all you had.", "author": "Angela Bassett"},
    {"text": "The only thing that overcomes hard luck is hard work.", "author": "Harry Golden"},
    {"text": "A man can make what he wants of himself if he truly believes that he must be ready for hard work and many heartbreaks.", "author": "Thurgood Marshall"},
    {"text": "Motivation will almost always beat mere talent.", "author": "Norman Ralph Augustine"},
    {"text": "Let me tell you the secret that has led me to my goals: my strength lies solely in my tenacity.", "author": "Louis Pasteur"},
    {"text": "Dreams are lovely. But they are dreams. Fleeting, ephemeral, pretty. But dreams do not come true just because you dream them. It's hard work that makes things happen.", "author": "Shonda Rhimes"},
    {"text": "You may encounter many defeats, but you must not be defeated.", "author": "Maya Angelou"},
    {"text": "Obstacles can't stop you. Problems can't stop you. Most of all, other people can't stop you. Only you can stop you.", "author": "Jeffrey Gitomer"},
    {"text": "Always do your best. What you plant now, you will harvest later.", "author": "Og Mandino"},
    {"text": "Instead of looking at the past, I put myself ahead 20 years and try to look at what I need to do now in order to get there then.", "author": "Diana Ross"},
    {"text": "Without hustle, talent will only carry you so far.", "author": "Gary Vaynerchuk"},
    {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
    {"text": "Setting goals is the first step in turning the invisible into the visible.", "author": "Tony Robbins"},
    {"text": "Talent is nothing without persistence.", "author": "Dean Crawford"},
    {"text": "Persistence is the twin sister of excellence. One is a matter of quality; the other, a matter of time.", "author": "Marabel Morgan"},
    {"text": "You never know what's around the corner. It could be everything. Or it could be nothing. You keep putting one foot in front of the other, and then one day you look back and you've climbed a mountain.", "author": "Tom Hiddleston"},
    {"text": "A little more persistence, a little more effort and what seemed hopeless failure may turn to glorious success.", "author": "Elbert Hubbard"},
    {"text": "Perseverance is the hard work you do after you get tired of doing the hard work you already did.", "author": "Newt Gingrich"},
    {"text": "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", "author": "Winston Churchill"},
    {"text": "If you get tired, learn to rest, not to quit.", "author": "Banksy"},
    {"text": "Perseverance is not a long race; it is many short races one after the other.", "author": "Walter Elliot"},
    {"text": "The only thing standing between you and outrageous success is continuous progress.", "author": "Dan Waldschmidt"},
    {"text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle"},
    {"text": "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", "author": "Dale Carnegie"},
    {"text": "Your talent determines what you can do. Your motivation determines how much you're willing to do. Your attitude determines how well you do it.", "author": "Lou Holtz"},
    {"text": "The happiness of your life depends on the quality of your thoughts.", "author": "Marcus Aurelius"},
    {"text": "Nothing is impossible. The word itself says 'I'm possible!'", "author": "Audrey Hepburn"},
    {"text": "The only person you need to be better than is the person you were yesterday.", "author": None},
    {"text": "Fall in love with taking care of yourself. Mind. Body. Spirit.", "author": None},
    {"text": "Push yourself because no one else is going to do it for you.", "author": None},
    {"text": "Success starts with self-discipline.", "author": None},
    {"text": "Your desire to change must be greater than your desire to stay the same.", "author": None},
    {"text": "Don't decrease the goal. Increase the effort.", "author": "Tom Coleman"},
]

db = SessionLocal()

count = 0
for q in quotes_data:
    quote = Quote(text=q["text"], author=q["author"])
    db.add(quote)
    count += 1

db.commit()
print(f"Seeded {count} quotes successfully")